pool:
  name: 'Default'
container: mcr.microsoft.com/dotnet/sdk:6.0
steps:
- script: dir
  displayName: Gets the current date
- script: dir  
  workingDirectory: $(Agent.BuildiDirectory)
  displayName: list the content of a folder
